# This playbook install a dropbear ssh server
# (https://matt.ucc.asn.au/dropbear/dropbear.html).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install dropbear package
  yum: pkg=$item
       state=present 
  with_items:
    - dropbear

- name: enable switch to port 222
  template: src=files/dropbear-config.j2 
            dest=/etc/sysconfig/dropbear
            owner=root
            group=root
            mode=0644

- name: configure firewall, allow ssh traffic
  command: /usr/bin/firewall-cmd --permanent --add-port=222/tcp

- name: reload firewall configuration
  command: /usr/bin/firewall-cmd --reload

- name: start dropbear
  service: name=dropbear
           state=running
           enabled=yes
