# This playbook install the openssh server (http://www.openssh.org/).
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install openssh package
  yum: pkg={{ item }}
       state=present 
  with_items:
    - openssh-server
    - xorg-x11-xauth

- name: configure firewall, allow traffic to port 22
  firewalld: port=22/tcp
             permanent=true
             state=enabled

- name: start openssh
  service: name=sshd
           state=running
           enabled=yes
