# This playbook install the openssh server (http://www.openssh.org/).
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install openssh package
  yum: pkg={{ item }}
       state=present 
  with_items:
    - openssh-server
    - xorg-x11-xauth

- name: configure firewall, allow ssh traffic
  command: /usr/bin/firewall-cmd --permanent --add-port=22/tcp

- name: reload firewall configuration
  command: /usr/bin/firewall-cmd --reload

- name: start openssh
  service: name=ssh
           state=running
           enabled=yes
