# This playbook contains tasks to perform on a fresh Fedora installation to
# create a Fedora Security Lab Test bench. 
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# Usage: ansible-playbook setup.yml -f 10
# 
---
- hosts: fsl-tb
  user: root
  vars_files:
    - variables/application-versions.yml
    - variables/sensitive-variables.yml

  tasks:
# Common tasks
    - include: tasks/preparation.yml
    - include: tasks/motd.yml
    - include: tasks/lighttpd.yml
    - include: tasks/mysql.yml

# FSL Test bench specific stuff
    - include: tasks/website.yml
    - include: tasks/helpers/log-system.yml
    - include: tasks/helpers/cgi.yml
    - include: tasks/helpers/phpinfo.yml
    - include: tasks/helpers/php-shell-detector.yml
    - include: tasks/helpers/linfo.yml
    - include: tasks/helpers/phpmyadmin.yml

# Vulnerable Web Application
    - include: tasks/apps/sqlol.yml
    - include: tasks/apps/sqli.yml
    - include: tasks/apps/bwapp.yml
    - include: tasks/apps/dvwa.yml
#    - include: tasks/apps/wacko.yml

# Honeypot
    - include: tasks/honeyd.yml
#    - include: tasks/artillery.yml
#    - include: tasks/kippo.yml

# Shells
#    - include: tasks/shells/ani-shell.yml
#    - include: tasks/shells/wso.yml
#    - include: tasks/shells/escobar.yml
    - include: tasks/shells/b374k.yml
    - include: tasks/shells/dnashell.yml
    - include: tasks/shells/phpshell.yml

# Common tasks
    - include: tasks/cleanup.yml

  handlers:
   - include: handlers/system.yml
   - include: handlers/services.yml
