# This playbook install all packages for the Fedora Security Lab.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved. 
#
# Synced at 2013-05-08
#
---
- hosts: fsl_hosts
  user: root
  tasks:
  - name: install $item
    action: yum pkg=$item state=installed
    with_items:
       - ArpOn
       - afftools
       - aide
       - aircrack-ng
       - airsnort
       - argus
       - binwalk
       - bkhive
       - bonesi
       - chkrootkit
       - cmospwd
       - cowpatty
       - dc3dd
       - ddrescue
       - dhcping
       - dnsenum
       - dnsmap
       - dnstop
       - dnstracer
       - driftnet
       - dsniff
       - echoping
       - etherape
       - ettercap
       - ettercap-gtk
       - examiner
       - firewalk
       - firstaidkit-gui
       - firstaidkit-plugin-all
       - flawfinder
       - foremost
       - gparted
       - halberd
       - hexedit
       - hfsutils
       - honeyd
       - horst
       - hping3
       - ht
       - httping
       - httpry
       - hunt
       - iftop
       - iperf
       - iptraf-ng
       - irssi
       - john
       - kismet
       - kismon
       - labrea
       - lbd
       - lynis
       - macchanger
       - mc
       - mcabber
       - medusa
       - mutt
       - nano
       - nbtscan
       - nc
       - nc6
       - ncrack
       - nebula
       - net-snmp
       - nethogs
       - netsed
       - netsniff-ng
       - ngrep
       - nikto
       - nload
       - nmap
       - nmap-frontend
       - nmbscan
       - ntfs-3g
       - ntfsprogs
       - ntop
       - nwipe
       - onesixtyone
       - openvas-client
       - openvas-scanner
       - ophcrack
       - p0f
       - packETH
       - pads
       - paris-traceroute
       - pcapdiff
       - pdfcrack
       - picviz-gui
       - powertop
       - prelude-lml
       - prelude-manager
       - prewikka
       - proxychains
       - pscan
       - pyrit
       - raddump
       - ratproxy
       - rats
       - rkhunter
       - safecopy
       - samdump2
       - scalpel
       - scamper
       - scanmem
       - scapy
       - screen
       - scrub
       - sectool-gui
       - security-menus
       - siege
       - sing
       - sipp
       - sipsak
       - skipfish
       - sleuthkit
       - slowhttptest
       - snmpcheck
       - socat
       - splint
       - sqlninja
       - srm
       - sshscan
       - ssldump
       - sslscan
       - sslstrip
       - sucrack
       - swaks
       - tcpdump
       - tcpflow
       - tcpick
       - tcpjunk
       - tcpreen
       - tcpreplay
       - tcpxtract
       - telnet
       - testdisk
       - trafshow
       - tripwire
       - unhide
       - unicornscan
       - uperf
       - vim-enhanced
       - vnstat
       - wavemon
       - wbox
       - weplab
       - wget
       - whois
       - wipe
       - wireshark-gnome
       - xmount
       - xprobe2
       - yersinia
       - yum-utils
