# This playbook contains all tasks to setup a Fedora Security Lab test bench as
# virtual machine.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# Usage: sudo ansible-playbook fsl-test-bench/local-setup.yml --connection=local
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  user: root
  vars_files:
    - variables/application-versions.yml
    - variables/sensitive-variables.yml
  vars:
################################################################################
# Those vars are for the virtual machine.
    - language: en_US.UTF-8
    - keyboard: sg-latin1
    - timezone: Europe/Zurich
    - virtname: FSL-Test-bench
    - ram: 1024
    - size: 5
    - network: 'network:testbench'
    - ip: 10.1.1.5
    - gw: 10.1.1.1
    - range_start: 10.1.1.5
    - range_end: 10.1.1.50
    - mac: '52:52:00:00:00:01'
    - mirror: http://mirror.switch.ch/ftp/mirror/fedora/linux/releases/18/Fedora/x86_64/os/
################################################################################
  tasks:
# Virtual machine setup tasks
    - include: tasks/mc.yml # Just a playbook to test the local connection
    - include: tasks/libvirt.yml
    - include: tasks/virt-install.yml

    - name: start the virtual machine
      virt: name=$virtname
            state=running

# Setup Test bench connection
    - include: tasks/auth-key.yml

    - name: setup host file
      lineinfile: dest=/etc/ansible/hosts
              regexp='^'
              insertafter='127.0.0.1'
              line='127.0.0.1\n\n[fsl-tb]\n$ip'

  handlers:
   - include: handlers/system.yml
   - include: handlers/services.yml
###############################################################################
# Setup the Test bench
- hosts: fsl-tb
  user: root
  vars_files:
    - variables/application-versions.yml
    - variables/sensitive-variables.yml

  tasks:
# Common tasks
    - include: tasks/preparation.yml
    - include: tasks/motd.yml
    - include: tasks/hosts.yml
    - include: tasks/users.yml

# Services
    - include: tasks/web-servers/lighttpd.yml
    - include: tasks/web-servers/nginx.yml
    - include: tasks/web-servers/tomcat.yml
    - include: tasks/web-servers/pywebserve.yml
    - include: tasks/web-servers/nodejs.yml
    - include: tasks/db-servers/mysql.yml
    - include: tasks/ftp-servers/vsftpd.yml
    - include: tasks/misc-servers/dropbear.yml
    - include: tasks/misc-servers/tftp.yml
    - include: tasks/misc-servers/telnet.yml
    - include: tasks/misc-servers/cups.yml
    - include: tasks/file-servers/samba.yml
    - include: tasks/file-servers/nfs.yml
    - include: tasks/misc-servers/openvpn-static.yml
    - include: tasks/mail-servers/postfix.yml
    - include: tasks/mail-servers/dovecot.yml

# FSL Test bench specific stuff
    - include: tasks/website.yml

# Helpers
    - include: tasks/helpers/log-system.yml
    - include: tasks/helpers/cgi.yml
    - include: tasks/helpers/phpinfo.yml
    - include: tasks/helpers/php-shell-detector.yml
    - include: tasks/helpers/linfo.yml
    - include: tasks/helpers/phpmyadmin.yml

# Vulnerable Web Application
    - include: tasks/apps/sqlol.yml
    - include: tasks/apps/sqli.yml
    - include: tasks/apps/bwapp.yml
    - include: tasks/apps/dvwa.yml
    - include: tasks/apps/hackademic.yml
    - include: tasks/apps/xssed.yml

# Honeypots
    - include: tasks/honeypots/honeyd.yml

# Shells
    - include: tasks/shells/b374k.yml
    - include: tasks/shells/dnashell.yml
    - include: tasks/shells/phpshell.yml
    - include: tasks/shells/ajaxshell.yml

# Common tasks
    - include: tasks/cleanup.yml

  handlers:
   - include: handlers/system.yml
   - include: handlers/services.yml
