# This playbook contains all tasks to perform on a fresh Fedora installation to
# create a Hacker Highschool Test bench.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# Usage: sudo ansible-playbook fsl-test-bench/local-setup.yml --connection=local
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  user: root
  vars_files:
    - variables/application-versions.yml
    - variables/sensitive-variables.yml
  vars:
################################################################################
# Those vars are for the virtual machine.
    - language: en_US.UTF-8
    - keyboard: sg-latin1
    - timezone: Europe/Zurich
    - virtname: FSL-Test-bench
    - ram: 1024
    - size: 5
    - network: 'network:testbench'
    - ip: 10.1.1.5
    - gw: 10.1.1.1
    - range_start: 10.1.1.5
    - range_end: 10.1.1.50
    - mac: '52:52:00:00:00:01'
    - mirror: http://mirror.switch.ch/ftp/mirror/fedora/linux/releases/18/Fedora/x86_64/os/
################################################################################

  tasks:
# Virtual machine setup tasks
#    - include: tasks/mc.yml # Just a playbook to test the local connection
    - include: tasks/libvirt.yml
    - include: tasks/virt-install.yml

    - name: start the virtual machine
      virt: name=$virtname
            state=running

  handlers:
   - include: handlers/system.yml
   - include: handlers/services.yml
