# This playbook install the samba (http://www.samba.org/) server.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install the needed packages
  command: /usr/bin/dnf -y install $item 
  with_items:
    - cups-libs
    - samba
    - samba-common
    - samba-client

- name: start samba
  service: name=smb
           state=running
           enabled=yes
