# This playbook install the proftpd server (http://www.proftpd.org).
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install proftpd package
  yum: pkg={{ item }}
       state=present 
  with_items:
    - proftpd

- name: start proftpd
  service: name=proftpd
           state=running
           enabled=yes 

- name: configure firewall, allow ftp traffic
  firewalld: service=ftp
             permanent=true
             state=enabled
