# This playbook remove all components which were needed for the setup. 
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: remove the unzip package
  command: /usr/bin/dnf -y erase unzip

- name: remove the tar package
  command: /usr/bin/dnf -y erase tar

- name: remove git
  command: /usr/bin/dnf -y erase git

- name: cleaning task for yum
  command: /usr/bin/yum clean all

- name: cleaning task for dnf
  command: /usr/bin/dnf clean all

- name: delete caches files
  file: path=/var/cache/$item
        state=absent
  with_items:
    - yum
    - dnf
