# This playbook install a dropbear ssh server
# (https://matt.ucc.asn.au/dropbear/dropbear.html).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install needed packages
  command: /usr/bin/dnf -y install $item 
  with_items:
    - dropbear

- name: configure firewall, allow ipp traffic
  command: /usr/bin/firewall-cmd --permanent --add-service=ssh

- name: reload firewall configuration
  command: /usr/bin/firewall-cmd --reload

- name: start dropbear
  service: name=dropbear
           state=running
           enabled=yes
