# This playbook install and setup libvirt (http://libvirt.org/).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# All rights reserved. Licensed under CC BY 3.0
#
---
- name: install the needed packages
  command: /usr/bin/dnf -y install $item
  with_items:
    - bridge-utils
    - libvirt
    - libvirt-client
    - libvirt-daemon-qemu
    - libvirt-daemon-kvm

- name: start libvirtd
  service: name=libvirtd
           state=running
           enabled=yes
