# This playbook install the lighttpd with FastCGI and PHP.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install the lighttpd web server
  command: /usr/bin/dnf -y install lighttpd

- name: install php packages
  command: /usr/bin/dnf -y install $item 
  with_items:
    - lighttpd-fastcgi
    - php-cli

- name: enable fastcgi support in modules.conf
  lineinfile: dest=/etc/lighttpd/modules.conf
              regexp='^include "conf.d/fastcgi.conf"'
              insertafter='^#include "conf.d/fastcgi.conf"'
              line='include "conf.d/fastcgi.conf"'
              state=present

- name: enable fastcgi support
  template: src=files/fastcgi.j2 
            dest=/etc/lighttpd/conf.d/fastcgi.conf
            owner=lighttpd
            group=lighttpd
            mode=0644

- name: enable lighttpd on boot
  command: systemctl enable lighttpd.service
# Why is this not working?
#  service: name=lighttpd enabled=yes
#  service: name=lighttpd.service enabled=yes
# -> msg: service name not recognized
# Seems to be a bug

- name: configure firewall, allow http traffic
  command: firewall-cmd --permanent --add-service=http

- name: remove lighttpd default file (images)
  file: path=/var/www/lighttpd/$item
        state=absent
  with_items:
    - index.html
    - light_logo.png
    - favicon.ico
    - light_button.png
    - poweredby.png
