# This playbook install the SQLol SQL injection test-bed
# application (https://github.com/SpiderLabs/SQLol).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: to use the git module later, git is needed
  command: /usr/bin/dnf -y install git

- name: delete a previous checkout
  file: path=/var/www/lighttpd/sqlol
        state=absent

- name: checkout the source
  command: /usr/bin/git clone git://github.com/SpiderLabs/SQLol.git /var/www/lighttpd/sqlol

- name: set the default mysql password
  command: /usr/bin/sed -i "s|$password = ''|$password = '$mysql_root_password'|g" /var/www/lighttpd/sqlol/includes/database.config.php

- name: set the right permission
  file: path=/var/www/lighttpd/
        mode=0777
        state=directory

- name: add a new entry to the index.html page
  lineinfile: dest=/var/www/lighttpd/index.html
              regexp='^<!--VA-->'
              insertafter='        <!--VA-->'
              line='        <a href="/sqlol" class="btn btn-primary">SQLol</a>'

- name: remove git
  command: /usr/bin/dnf -y erase git
