# This playbook install the default html files incl. bootstrap. 
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: download the bootstrap zip archive
  get_url: url=http://twitter.github.com/bootstrap/assets/bootstrap.zip
           dest=/var/www/lighttpd/bootstrap.zip
           mode=0440

- name: unpack the bootstrap archive
  command: /usr/bin/unzip -o /var/www/lighttpd/bootstrap.zip -d /var/www/lighttpd/

- name: delete the bootstrap archive
  file: path=/var/www/lighttpd/bootstrap.zip
        state=absent

- name: download the jquery library
  get_url: url=http://code.jquery.com/jquery-$jquery_version.min.js
           dest=/var/www/lighttpd/bootstrap/js/jquery.min.js
           mode=0775

- name: install the fsl test bench index.html file
  template: src=files/website/index.j2
            dest=/var/www/lighttpd/index.html 
            owner=root
            group=root
            mode=0644

- name: install the fsl test bench about.html file
  template: src=files/website/about.j2
            dest=/var/www/lighttpd/about.html 
            owner=root
            group=root
            mode=0644

- name: install the fsl test bench contact.html file
  template: src=files/website/contact.j2
            dest=/var/www/lighttpd/contact.html 
            owner=root
            group=root
            mode=0644

- name: copy the fsl banner
  copy: src=files/website/Spins-banner_security.png
        dest=/var/www/lighttpd/Spins-banner_security.png
        owner=root
        group=root
        mode=0644
