# This playbook install a dovecot (http://dovecot.org/) server.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install dovecot packages
  yum: pkg={{ item }}
       state=present 
  with_items:
    - dovecot

- name: default dovecot configuration file
  template: src=files/dovecot-config.j2
            dest=/etc/dovecot/dovecot.conf
            owner=root
            group=root
            mode=0644

- name: enable maildir support
  lineinfile: dest=/etc/dovecot/conf.d/10-mail.conf
              regexp='^mail_location ='
              insertafter='^#mail_location ='
              line='mail_location = maildir:~/Maildir'
              state=present

- name: configure firewall, allow encrypted traffic
  firewalld: service={{ item }}
             permanent=true
             state=enabled
  with_items:
     - pop3s
     - imaps

- name: configure firewall, allow plaintext traffic
  firewalld: port={{ item }}/tcp
             permanent=true
             state=enabled
  with_items:
     - 110
     - 143

- name: start dovecot
  service: name=dovecot
           state=running
           enabled=yes
