# This playbook install a dovecot (http://dovecot.org/) server.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install needed packages
  command: /usr/bin/dnf -y install $item 
  with_items:
    - dovecot

- name: default dovecot configuration file
  template: src=files/dovecot-config.j2
            dest=/etc/dovecot/dovecot.conf
            owner=root
            group=root
            mode=0644

- name: enable maildir support
  lineinfile: dest=/etc/dovecot/conf.d/10-mail.conf
              regexp='^mail_location ='
              insertafter='^#mail_location ='
              line='mail_location = maildir:~/Maildir'
              state=present

- name: configure firewall, allow pop traffic
  command: /usr/bin/firewall-cmd --permanent --add-port=110/tcp

- name: configure firewall, allow imap traffic
  command: /usr/bin/firewall-cmd --permanent --add-port=143/tcp

- name: configure firewall, allow pop3s traffic
  command: /usr/bin/firewall-cmd --permanent --add-service=pop3s

- name: configure firewall, allow imaps traffic
  command: /usr/bin/firewall-cmd --permanent --add-service=imaps

- name: reload firewall configuration
  command: /usr/bin/firewall-cmd --reload

- name: start dovecot
  service: name=dovecot
           state=running
           enabled=yes
