# This playbook install a postfix (http://www.postfix.org/) server.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install postfix packages
  yum: pkg={{ item }}
       state=present 
  with_items:
    - postfix

- name: default postfix configuration file
  template: src=files/postfix-config.j2
            dest=/etc/postfix/main.cf
            owner=root
            group=root
            mode=0644

- name: configure firewall, allow traffic to port 25
  firewalld: port=25/tcp
             permanent=true
             state=enabled

- name: start postfix
  service: name=postfix
           state=running
           enabled=yes
