# This playbook install Bricks (http://sechow.com/brick).
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: download the latest bricks archive
  get_url: url=http://sourceforge.net/projects/owaspbricks/files/Tuivai%20-%202.2/OWASP%20Bricks%20-%20Tuivai.zip
           dest=/var/www/lighttpd/bricks.zip
           mode=0440

- name: unpack the source archive
  unarchive: src=/var/www/lighttpd/bricks.zip
             dest=/var/www/lighttpd/
             copy=no
             mode=0775
             owner=lighttpd
             group=lighttpd

- name: delete the bricks archive
  file: path=/var/www/lighttpd/bricks.zip
        state=absent

- name: install a default configuration file
  template: src=files/bricks.j2
            dest=/var/www/lighttpd/bricks/LocalSettings.php
            owner=root
            group=root
            mode=0755

- name: create database for bricks
  mysql_db: name=bricks
            state=present 

- name: add a new entry to the index.html page
  lineinfile: dest=/var/www/lighttpd/index.html
              regexp='^<!--VA-->'
              insertafter='        <!--VA-->'
              line='        <a href="/bricks" class="btn btn-default">Bricks</a></br>'
