# This playbook install the OWASP Hackademic Challenges Project 
# (https://code.google.com/p/owasp-hackademic-challenges/).
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: download the hackademic archive
  get_url: url=https://owasp-hackademic-challenges.googlecode.com/files/OWASP_Hackademic_Challenges_en_v{{ hackadamemic_version }}.zip
           dest=/var/www/lighttpd/hackademic-{{ hackadamemic_version }}.zip
           mode=0440

- name: unpack the source archive
  unarchive: src=/var/www/lighttpd/hackademic-{{ hackadamemic_version }}.zip
             dest=/var/www/lighttpd/
             copy=no
             mode=0775
             owner=lighttpd
             group=lighttpd

- name: delete the hackademic archive
  file: path=/var/www/lighttpd/hackademic-{{ hackadamemic_version }}.zip
        state=absent

- name: rename the hackademic directory
  command: /usr/bin/mv /var/www/lighttpd/Hackademic_Challenges[EN]/Hackademic_Challenges /var/www/lighttpd/hackademic

- name: delete the unpacked archive elements
  file: path=/var/www/lighttpd/Hackademic_Challenges[EN]
        state=absent

- name: set permissons
  file: path=/var/www/lighttpd/hackademic
        state=directory
        mode=0755

- name: add a new entry to the index.html page
  lineinfile: dest=/var/www/lighttpd/index.html
              regexp='^<!--VA-->'
              insertafter='        <!--VA-->'
              line='        <a href="/hackademic" class="btn btn-default">Hackademic</a></br>'
