# This variables file contains the version numbers of the software packages
# which will be installed without the package management tool and basic release
# number as helper variables for playbooks.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
# Fedora - http://fedoraproject.org
fedora_previous: 18
fedora_current: 19
fedora_next: 20

# Bootstrap - http://getbootstrap.com/
bootstrap_version: 3.0.0

# linfo - http://linfo.sourceforge.net/
linfo_version: 1.9

# phpshell - http://phpshell.sourceforge.net/
phpshell_version: 2.4

# Damn Vulnerable Web App (DVWA) - http://www.dvwa.co.uk/
dvwa_version: 1.0.8

# phpMyAdmin- http://www.phpmyadmin.net/
phpmyadmin_version: 4.0.9

# bWAPP - http://sourceforge.net/projects/bwapp/
bwapp_version: 1.3

# ani-shell - http://sourceforge.net/projects/ani-shell/
ani_version: 1.5

# jQuery - http://jquery.com
jquery_version: 1.10.2

# kippo - http://code.google.com/p/kippo
kippo_version: 0.5

# hackadamemic - https://code.google.com/p/owasp-hackademic-challenges/
hackadamemic_version: 0.1.1
