# This playbook install the ani-shell (http://sourceforge.net/projects/ani-shell).
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: create the directory
  file: path=/var/www/lighttpd/ani-shell
        state=directory

- name: download the source tarball
  get_url: url=http://downloads.sourceforge.net/project/ani-shell/Ani-Shell%20v{{ ani_version }}/Ani-Shell%20v{{ ani_version }}.zip
           dest=/var/www/lighttpd/ani-shell-{{ ani_version }}.zip
           mode=0440

- name: unpack the archive
  command: /usr/bin/unzip -o /var/www/lighttpd/ani-shell-{{ ani_version }}.zip -d /var/www/lighttpd/ani-shell

- name: delete the archive
  file: path=/var/www/lighttpd/ani-shell-{{ ani_version }}.zip
        state=absent

- name: remove unneeded files
  file: path=/var/www/lighttpd/ani-shell/{{ item }}
        state=absent
  with_items:
    - README.txt
    - __MACOSX

- name: no login
  command: /usr/bin/sed -i 's|$lock = "on";|$lock = "off";|g' /var/www/lighttpd/ani-shell/Ani-Shell.php

- name: add a new entry to the index.html page
  lineinfile: dest=/var/www/lighttpd/index.html
              regexp='^<!--SH-->'
              insertafter='            <!--SH-->'
              line='            <a href="/ani-shell/Ani-Shell.php" class="btn btn-default">Ani-Shell</a></br>'
