# This playbook install the Esc0b4r PHP shell 
# (http://sourceforge.net/projects/esc0b4rshell/).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: create the directory
  file: path=/var/www/lighttpd/escobar
        state=directory

- name: download the source
  get_url: url=http://downloads.sourceforge.net/project/esc0b4rshell/esc0b4r.php
           dest=/var/www/lighttpd/escobar/esc0b4r.php
           mode=0775

- name: add a new entry to the index.html page
  lineinfile: dest=/var/www/lighttpd/index.html
              regexp='^<!--SH-->'
              insertafter='            <!--SH-->'
              line='            <a href="/escobar/esc0b4r.php" class="btn btn-default">Esc0b4r</a></br>'
