# This playbook install the openldap (http://www.lighttpd.net/) server.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install the needed packages
  command: /usr/bin/dnf -y install $item 
  with_items:
    - openldap
    - openldap-clients
    - openldap-servers

- name: start openldap
  service: name=slapd
           state=running
           enabled=yes
