# This playbook install the darkhttpd (http://unix4lyfe.org/darkhttpd/) web
# server.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install darkhttpd package
  yum: pkg={{ item }}
       state=present 
  with_items:
    - darkhttpd

- name: create a directory for darkhttpd
  file: path=/var/www/darkhttpd
        mode=0755
        state=directory

- name: enable darkhttpd options
  template: src=files/darkhttpd-config.j2 
            dest=/etc/sysconfig/darkhttpd
            owner=root
            group=root
            mode=0644

- name: start darkhttpd
  service: name=darkhttpd
           state=running
           enabled=yes 

- name: configure firewall, allow http traffic
  command: /usr/bin/firewall-cmd --permanent --add-port=8887/tcp

- name: reload firewall configuration
  command: /usr/bin/firewall-cmd --reload

- name: install a default index.html file
  template: src=files/website/default.j2 
            dest=/var/www/darkhttpd/index.html
            owner=root
            group=root
            mode=0644
