# This playbook install a simple file for displaying details about the PHP
# installation.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: create the directory for phpinfo
  file: path=/var/www/lighttpd/phpinfo
        owner=root
        group=root
        mode=0775
        state=directory

- name: install the index.php file
  template: src=files/web-interface/phpinfo.j2
            dest=/var/www/lighttpd/phpinfo/index.php
            owner=lighttpd
            group=lighttpd
            mode=0644

- name: add a new entry to the index.html page
  lineinfile: dest=/var/www/lighttpd/index.html
              regexp='^<!--IN-->'
              insertafter='        <!--IN-->'
              line='        <a href="/phpinfo/index.php" class="btn btn-default">phpInfo</a></br>'
